# general settings
name: test_MMYOLO
model_type: MMYOLO
phase: test
num_gpu: 1
manual_seed: 0


# dataset and data loader settings
datasets:
  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    name: val
    type: OSLSPdet_FusionDataset
    crop_size: 320
    LW_path: '/data/NSLSR_test/LWIR/'
    SW_path: '/data/NSLSR_test/SWIR/'
    label_path: '/data/NSLSR_test/labels/'
    is_crop: True
    is_size: False
    is_pad: False
    batch_size_per_gpu: 8
    num_worker_per_gpu: 8
    pin_memory: True
    data_len: -1


# network structures
network_detfusion:
  type: MMYOLO

Det_labels:
  nc: 1
  conf: 0.01
  iou: 0.7
  iou_thres: 0.45
  names: ['Ship'] #['ship','car','person']
  conf_save: 0.25

# path
path:
  pretrain_network_MMFusion: ~
  pretrain_network_MMYOLO: /LSFDNet-main/PTH/net_LSFDNet.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  a: 0.8 
  b: 0.5 
  c: 0.5  
  loss_dict: [6000, 30000]
  #n_epoch: 300
  optimizer:
    type: Adam
    lr: !!float 2e-4

  scheduler:
    type: MultiStepLR
    milestones: [4000, 10000, 16000, 24000, 32000, 40000, 60000, 80000, 100000, 200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # -1 no warm up

  #Loss
  Loss_OE:
    type: FusionDetloss_OE
    device: cuda

val:
  pbar: true
  start_val: 0
  val_freq: !!float 500
  save_img: true
  suffix: false
  plot_det: true
 
  metrics:
    EN: 
      type: ~
    SF: 
      type: ~
    AG: 
      type: ~
    SD: 
      type: ~
    CC: 
      type: ~
    SCD: 
      type: ~
    MSE: 
      type: ~
      better: lower
    PSNR: 
      type: ~
    Qabf: 
      type: ~
    Nabf: 
      type: ~
      better: lower


# logging settings
logger:
  print_freq: 50
  start_save: 0
  save_checkpoint_freq: !!float 500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
